db:
  database: ggs2025_db
  user: ggs2025_admin
  port: 5433
  password: PONER_PASSWORD
install:
  dump:
    db:
      owner: ggs2025_owner
  table-data-dir: 
    - ../dmencu-data/ggs2025
    - ../dmencu-data/templates_app_final #no borrar, dejar último, chequea los tabs obligatorios al correr -- --dump-db
login:
  plus:
    secret: PONERSECRET
    allowHttpLogin: true
devel:
  forceShowAsEditable: false
  useFileDevelopment: true
client-setup:
  skin: ""
  lang: es
server:
  skins:
    confort:
      local-path: ../backend-skins/dist/
