db:
  database: ggs2026_db
  user: ggs2026_admin
  port: 5433
  password: PONER_PASSWORD
install:
  dump:
    db:
      owner: ggs2026_owner
  table-data-dir: 
    - ../dmencu-data/ggs2026
    - ../dmencu-data/templates_app_final #no borrar, dejar último, chequea los tabs obligatorios al correr -- --dump-db
login:
  plus:
    secret: PONERSECRET
    allowHttpLogin: true
    loginForm:
      formTitle: GGS2026
devel:
  forceShowAsEditable: false
  useFileDevelopment: true
client-setup:
  skin: ""
  background-img: ""
  lang: es
  title: GGS2026
  operativo: ggs2026
server:
  skins:
    confort:
      local-path: ../backend-skins/dist/
