set search_path to base;

INSERT INTO casilleros (
operativo,padre,tipoc,casillero,orden,es_activo,nombre,tipovar,longitud,tipoe,aclaracion,salto,
unidad_analisis,cantidad_resumen,despliegue,ver_id,optativo,formulario_principal,var_name,
var_name_especial,expresion_habilitar,valor_ns_nc,valor_sin_dato,leer,calculada,libre,especial
)
VALUES
('GGS_2025',NULL,'F','TEM',10,TRUE,'TEM',NULL,NULL,NULL,NULL,NULL,'viviendas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','CARGA',100,TRUE,'Datos de la carga',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','RESULTADO',200,TRUE,'Resultado del último trabajo de campo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','RECEPCION',300,TRUE,'Recepción',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','1',999,TRUE,'Encuestador',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','2',999,TRUE,'No realizada x el encuestador',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','3',999,TRUE,'Recuperación',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','4',999,TRUE,'Supervisión de Recuperador',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','5',999,TRUE,'Supervisión encuestador',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','ftc',999,TRUE,'Fin de las tareas de campo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:TEM','B','t_ing',999,TRUE,'TAREAS DE INGRESO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025',NULL,'F','RE',20,TRUE,'Resumen de formulario de la vivienda',NULL,NULL,NULL,NULL,NULL,'viviendas',NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','TEXTO','ResFor',5,TRUE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','vdominio',10,TRUE,NULL,'numero','1',NULL,NULL,NULL,NULL,NULL,'ocultar',NULL,NULL,NULL,'vdominio',NULL,'INHABILITAR',NULL,NULL,'false','true',NULL,NULL),
('GGS_2025','F:RE','P','obs_re',20,TRUE,'Observaciones','texto','ancho',NULL,NULL,NULL,NULL,NULL,NULL,'-','true',NULL,'obs_re',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:RE','TEXTO','vis_enunciado',30,TRUE,'Anote las visitas a la vivienda que haya realizado:',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','BF','BF_VIS',40,TRUE,'Visitas',NULL,'1',NULL,NULL,'VIS',NULL,'3',NULL,NULL,NULL,NULL,NULL,NULL,'total_vis',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:RE','P','total_vis',50,TRUE,'Total visitas:','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'total_vis',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:RE','P','Soporte',60,TRUE,'¿La encuesta se registra en papel o en Dispositivo Móvil?','opciones','1',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'soporte',NULL,'INHABILITAR',NULL,NULL,'false',NULL,NULL,'{"autoing":"2"}'),
('GGS_2025','Soporte','O','1',10,TRUE,'En papel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Soporte','O','2',20,TRUE,'En Dispositivo Móvil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','entreav',100,TRUE,'¿Existe la vivienda y está habitada?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'entreav',NULL,'INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','entreav','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','entreav','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,'razonv',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','identif',105,TRUE,'¿Identificó la vivienda  indicada  en la hoja de ruta?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'identif',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','identif','O','1',10,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','identif','O','2',20,TRUE,'No',NULL,NULL,NULL,NULL,'B.razon_viv',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','habita',106,TRUE,'Esa vivienda, ¿se encuentra en condiciones de ser habitada?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'habita',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','habita','O','1',10,TRUE,'Sí',NULL,NULL,NULL,NULL,'resid_hog',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','habita','O','2',20,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','construc',107,TRUE,'Construcción','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'construc',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','construc','O','1',10,TRUE,'Se está construyendo',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','construc','O','2',20,TRUE,'Construcción paralizada',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','construc','O','3',30,TRUE,'Refacción',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','B','B.razon_viv',108,TRUE,'Razón de no existencia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_viv','P','razon_viv',10,TRUE,'Razón por la cual la vivienda no existe','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'razon_viv',NULL,'identif=2',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_viv','O','2',2,TRUE,'Demolida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_viv','O','6',6,TRUE,'Variaciones en el listado',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_viv','P','razon_2',610,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 2',NULL,NULL,'razon2_2','razon2_2','razon_viv=2',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_2','O','1',21,TRUE,'Fue demolida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_2','O','2',22,TRUE,'En demolición',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_2','O','3',23,TRUE,'Levantada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_2','O','4',24,TRUE,'Tapiada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_viv','P','razon_6',630,TRUE,NULL,'opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'razón 6',NULL,NULL,'razon2_6','razon2_6','razon_viv=6',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_6','O','1',61,TRUE,'No existe lugar físico',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_6','O','2',62,TRUE,'No es vivienda',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_6','O','3',63,TRUE,'Existen otras viviendas',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_6','O','4',64,TRUE,'Otro',NULL,NULL,NULL,'especificar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_6/4','P','razon3',65,TRUE,NULL,'texto','medio',NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,'razon3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','resid_hog',109,TRUE,'En esa vivienda, ¿reside, al menos, un hogar particular?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'resid_hog',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','resid_hog','O','1',10,TRUE,'Sí',NULL,NULL,NULL,NULL,'contacto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','resid_hog','O','2',20,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','B','B.razon_hog',110,TRUE,'Razón de no existencia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog','P','razon_hog',10,TRUE,'Razón por la cual la vivienda no tiene habitantes permanentes','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'razon_hog',NULL,'resid_hog=2 or resid_hog=-9',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_hog','O','1',1,TRUE,'Deshabitada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_hog','O','3',3,TRUE,'Fin de Semana',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_hog','O','5',5,TRUE,'Vivienda usada como establecimiento',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_hog','O','9',10,TRUE,'Otras causas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog','P','razon_1',640,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 1',NULL,NULL,'razon2_1','razon2_1','razon_hog=1',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_1','O','1',1,TRUE,'Venta o alquiler',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_1','O','2',2,TRUE,'Sucesión o remate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_1','O','3',13,TRUE,'Construcción reciente',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_1','O','4',14,TRUE,'Sin causa conocida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog','P','razon_3',650,TRUE,NULL,'opciones',NULL,NULL,'Viven en otra vivienda la mayor parte...','fin',NULL,NULL,NULL,'razón 3','true',NULL,'razon2_3','razon2_3','razon_hog=3',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_3','O','1',31,TRUE,'de la semana',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_3','O','2',32,TRUE,'del mes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_3','O','3',33,TRUE,'del año',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog','P','razon_5',660,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 5',NULL,NULL,'razon2_5','razon2_5','razon_hog=5',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_5','O','1',51,TRUE,'Conserva comodidad de vivienda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog','P','razon_9v',670,TRUE,NULL,'opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'razon_9v',NULL,'razon_hog=9',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_9v','O','3',10,TRUE,'Problemas de seguridad',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_9v','O','4',20,TRUE,'Inaccesible',NULL,NULL,NULL,'(Problemas climáticos u otros)','fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_9v','O','7',30,TRUE,'No salió a campo',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_9v','O','8',40,TRUE,'Reservado',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','contacto',120,TRUE,'¿Alguna persona residente en la vivienda accedió a responder la encuesta?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'contacto',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','contacto','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','contacto','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','V1',140,TRUE,'¿Todas las personas que residen en esta vivienda comparten los gastos de comida?','si_no','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'v1',NULL,'contacto=1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','V1','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','V1','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','P','TOTAL_H',150,TRUE,'Total de hogares','numero','2',NULL,'Abra tantos cuestionarios S1 como cantidad de hogares',NULL,NULL,NULL,NULL,'-',NULL,NULL,'total_h',NULL,'v1=1 or v1=2 or contacto=2',NULL,NULL,NULL,NULL,NULL,'{"autoing":"v1 = 1 or contacto = 2=> 1"}'),
('GGS_2025','F:RE','CONS','V1_TotH=1',151,TRUE,'Si todos comparten los gastos, es un único hogar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(v1)) and v1=1 and not(blanco(total_h)) and total_h<>1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','CONS','V1_TotH>1',151,TRUE,'Si no comparten los gastos, debe haber más de un hogar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(v1)) and v1=2 and not(blanco(total_h)) and not(total_h>1)',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE','BF','BF_S1',810,TRUE,'Hogar',NULL,'1',NULL,NULL,'S1','viviendas','3',NULL,NULL,NULL,NULL,NULL,NULL,'total_h',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025',NULL,'F','VIS',30,TRUE,'Visitas de la vivienda',NULL,NULL,NULL,NULL,NULL,'visitas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:VIS','P','anoenc',10,TRUE,'Nro Renglon','numero','2',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'anoenc',NULL,'INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS','P','rol',20,TRUE,'Rol','texto','corto',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'rol',NULL,'INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS','P','per',30,TRUE,'Persona','numero','3',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'per',NULL,'INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS','P','usu',40,TRUE,'Usuario','texto','corto',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'usu',NULL,'INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS','P','fecha',50,TRUE,'Fecha visita','fecha','10',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'fecha',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS','P','hora',60,TRUE,'Hora','hora','4',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'hora',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS','P','anotacion',70,TRUE,'Anotación','texto','ancho',NULL,NULL,NULL,NULL,NULL,NULL,'-','true',NULL,'anotacion',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025',NULL,'F','S1',40,TRUE,'Carátula - componentes del hogar y vivienda',NULL,NULL,NULL,NULL,NULL,'hogares',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1','B','SM1.1',10,TRUE,'Apertura de la entrevista',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SM1.1','P','Observaciones',90,TRUE,'Observaciones','texto','ancho',NULL,NULL,NULL,NULL,NULL,NULL,'-','true',NULL,'observaciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SM1.1','FILTRO','Encuestables',100,TRUE,NULL,NULL,NULL,NULL,NULL,'razon',NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,'contacto = 1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SM1.1','P','GG1',160,TRUE,'¿En este hogar hay al menos una persona de 18 a 79 años de edad?','si_no','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'gg1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','GG1','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','GG1','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,'fijo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SM1.1','P','ENTREA',170,TRUE,'Apertura de entrevista','si_no','1',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'entrea',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','ENTREA','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','ENTREA','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,'razon',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SM1.1','P','F_REALIZ_O',180,TRUE,'Fecha de realización','fecha','10',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'f_realiz_o',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"autoing":"hoy()"}'),
('GGS_2025','SM1.1','CONS','valid_f_realiz_o',181,TRUE,'La fecha de realización debe ingresarse con formato dd/mm/aaaa',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'informado(f_realiz_o) and not(fecha_valida(f_realiz_o))',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SM1.1','P','fijo',190,TRUE,'¿Podría Ud. proveer un teléfono de contacto de su hogar (fijo o móvil) por si necesitamos confirmar o clarificar alguna de las preguntas?','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'fijo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SM1.1','FILTRO','Filtro_teléfono',195,TRUE,NULL,NULL,NULL,NULL,'sólo para personas en el rango de edad. El resto pasa a','fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'GG1=1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1','B','M.P',20,TRUE,'COMPONENTES DEL HOGAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P','P','los_nombres',1,TRUE,'Por favor, nombre todas las personas que componen este hogar empezando por usted. No se olvide de Ud. ni de bebés, niñas y niños.','texto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'los_nombres',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1','BF','BF_S1_P',25,TRUE,'Persona',NULL,'1',NULL,NULL,'S1_P',NULL,'3',NULL,NULL,NULL,NULL,NULL,NULL,'total_m',NULL,NULL,NULL,NULL,NULL,'{"camposResumen":["nombre","sexo","edad"]}'),
('GGS_2025','F:S1','B','CR',40,TRUE,'DATOS DEL HOGAR Y SORTEO DEL COMPONENTE SELECCIONADO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CR','P','total_m',210,TRUE,'Cantidad de componentes del hogar','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'total_m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CR','P','NOMBRER',220,TRUE,'Respondiente nombre','texto','texto',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'nombrer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CR','P','SORTEO',250,TRUE,'¿Esas son todas las personas que componen el hogar (incluidas las ausentes)?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sorteo',NULL,'_personas_incompletas=0',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SORTEO','O','1',10,TRUE,'Sí, son todas. Proceder al sorteo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SORTEO','O','2',20,TRUE,'No, faltó anotar a alguien',NULL,NULL,NULL,NULL,'total_m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CR','P','TP',300,TRUE,'Total de personas en el rango de edad','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'tp',NULL,'!!tp',NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','CR','P','MS',305,TRUE,'N° del componente seleccionado de 18 a 79 años','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'cr_num_miembro','cr_num_miembro','!!tp',NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','CR','P','MSNOMBRE',310,TRUE,'Nombre del componente seleccionado de 18 a 79 años','texto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'msnombre',NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','CR','P','cr_num_miembro_ing',320,TRUE,'Ingreso componente seleccionado','numero','2',NULL,'Si la encuesta es de Dominio 5 o se realizó en Papel',NULL,NULL,NULL,'ocultar','-','true',NULL,'cr_num_miembro_ing',NULL,'(soporte=1 or vdominio=5)',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1','BF','BF_I1',50,TRUE,'Individual',NULL,'1',NULL,NULL,'I1',NULL,'3',NULL,NULL,NULL,NULL,NULL,NULL,'total_m',NULL,NULL,NULL,NULL,NULL,'{"camposResumen":["nombre","sexo","edad"]}'),
('GGS_2025','F:S1','B','RAZON',90,TRUE,'RAZONES DE NO ENTREVISTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RAZON','P','razon',600,TRUE,'RAZÓN POR LA CUAL NO SE REALIZÓ LA ENTREVISTA','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'razon1','razon1','entrea=2 or contacto= 2',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon','O','7',7,TRUE,'Ausencia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon','O','8',8,TRUE,'Rechazo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon','O','9',9,TRUE,'Otras causas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RAZON','P','razon_7',680,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 7',NULL,NULL,'razon2_7','razon2_7','razon1=7',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_7','O','1',71,TRUE,'No se pudo contactar en tres visitas',NULL,NULL,NULL,'(presenciales o telefónicas)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7','O','2',72,TRUE,'Por causas circunstanciales',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7','O','3',73,TRUE,'Viaje',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7','O','4',74,TRUE,'Vacaciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7','O','5',75,TRUE,'Problemas con el dispositivo móvil',NULL,NULL,NULL,'(Robo, falla del servidor o del dispositivo, etc.)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7','O','6',76,TRUE,'Problemas con el teléfono',NULL,NULL,NULL,'(No corresponde, interferencia constante, dificultades en la red, etc.)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RAZON','P','razon_8',690,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 8',NULL,NULL,'razon2_8','razon2_8','razon1=8',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_8','O','1',81,TRUE,'Negativa rotunda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_8','O','2',82,TRUE,'Rechazo por portero eléctrico o teléfono',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_8','O','3',83,TRUE,'Se acordaron entrevistas que no se concretaron',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RAZON','P','razon_9h',700,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 9',NULL,NULL,'razon2_9','razon2_9','razon1=9',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_9h','O','2',2,TRUE,'Duelo, alcoholismo, discapacidad, idioma extranjero',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025',NULL,'F','S1_P',50,TRUE,'Personas',NULL,NULL,NULL,NULL,NULL,'personas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1_P','B','M.P_m',20,TRUE,'COMPONENTES DEL HOGAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','P1',170,TRUE,'Por favor, nombre todas las personas que componen este hogar, empezando por usted','texto','texto',NULL,'Nombre o sobrenombre. (No se olvide de Ud. ni de bebés, niñas y niños)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'nombre','nombre',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','P2a',180,TRUE,'Sexo registrado al nacer','opciones',NULL,NULL,'(Anote código).',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sexo','sexo',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P2a','O','1',1,TRUE,'Varón',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P2a','O','2',2,TRUE,'Mujer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p2_nsnc',181,TRUE,'En la pregunta p2 no se acepta la respuesta Ns/Nc. Verificar si es error de tipeo o de lo contrario justificar adecuadamente en observaciones.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(sexo)) and nsnc(sexo)',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','P3B',200,TRUE,'¿Cuántos años cumplidos tiene en este momento?','numero','2',NULL,'(Si tiene menos de un año anote 0).',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'edad','edad',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','edad_max',201,TRUE,'Edad ALTA confirme el dato',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(edad)) and not(nsnc(edad)) and edad>110',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','edad_positiva',201,TRUE,'La edad no debe ser negativa',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(edad)) and not(nsnc(edad)) and edad<0',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','P4',210,TRUE,'¿Qué parentesco tiene con usted? E-S','opciones','2',NULL,'(E-S) (Anote código).',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p4','p4',NULL,NULL,NULL,NULL,NULL,NULL,'{"autoing":"persona = 1 => 1"}'),
('GGS_2025','P4','O','1',1,TRUE,'Respondiente',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','2',2,TRUE,'Cónyuge/pareja',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','3',3,TRUE,'Hijo/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','4',4,TRUE,'Hijastro/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','5',5,TRUE,'Yerno o nuera',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','6',6,TRUE,'Nieto/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','7',7,TRUE,'Padre/madre/suegro/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','8',8,TRUE,'Hermano/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','9',9,TRUE,'Cuñado/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','10',10,TRUE,'Sobrino/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','11',11,TRUE,'Abuelo/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','12',12,TRUE,'Otro/a familiar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P4','O','14',14,TRUE,'Otro/a no familiar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','edad_nieto',211,TRUE,'Tiene mas de 65 años y figura como nieto del respondiente. Chequear que el dato sea correcto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'edad>65 and p4=6',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','edad_parent',211,TRUE,'Tiene doce años o menos y un parentesco con el/la respondiente poco frecuente para su edad (cónyuge, yerno, nuera, padre, madre, suegro/a o abuelo/a). Por favor chequear información',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(edad)) and not(nsnc(edad)) and edad<=12 and (p4=2 or p4=5 or p4=7 or p4=11)',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','mie1_p4=1',211,TRUE,'El miembro 1 debe ser el respondiente del hogar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'persona=1 and not(blanco(p4)) and p4<>1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','P4=1>=18',211,TRUE,'El/la respondiente preferentemente debe tener 18 años o más',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p4=1 and not(blanco(edad)) and not(nsnc(edad)) and edad<18',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p4=1_mie1',211,TRUE,'Si es respondiente del hogar debe ser miembro 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p4=1 and persona<>1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','LP',220,TRUE,'________________, ¿se encuentra presente en este momento?','si_no',NULL,NULL,'Para personas de 18 años a 79 años.',NULL,NULL,NULL,'ocultar',NULL,NULL,NULL,'lp',NULL,'edad>=18 and edad<=79 and vdominio=5',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','LP','O','1',10,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','LP','O','2',20,TRUE,'No',NULL,NULL,NULL,NULL,'P5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','L0',230,TRUE,'Letra de orden según edad','texto','texto',NULL,'Para personas de 18 años a 79 años. Comience con la letra A a partir de la persona de mayor edad y continúe con la letra B y subsiguientes. En dominio Villa, asigne letra únicamente a componentes del hogar que estén presentes en el momento de la entrevista',NULL,NULL,NULL,'ocultar',NULL,'true',NULL,'l0','l0','!!l0 or (edad >=18 and edad<=79)',NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','M.P_m','P','P5',240,TRUE,'¿Actualmente es... G-S','opciones','1',NULL,'Para personas de 14 años y más. (Anote código).',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p5','p5','edad>=14',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P5','O','1',1,TRUE,'unido/a?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P5','O','2',2,TRUE,'casado/a?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P5','O','3',3,TRUE,'separado/a de unión?',NULL,NULL,NULL,NULL,'filtro_p6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P5','O','4',4,TRUE,'viudo/a de unión?',NULL,NULL,NULL,NULL,'filtro_p6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P5','O','5',5,TRUE,'divorciado/a?',NULL,NULL,NULL,NULL,'filtro_p6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P5','O','6',6,TRUE,'separado/a de matrimonio?',NULL,NULL,NULL,NULL,'filtro_p6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P5','O','7',7,TRUE,'viudo/a de matrimonio?',NULL,NULL,NULL,NULL,'filtro_p6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P5','O','8',8,TRUE,'soltero/a, nunca casado/a ni unido/a?',NULL,NULL,NULL,NULL,'filtro_p6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','P4=2_P5',241,TRUE,'Si es cónyuge, debe ser unido/a o casado/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p4)) and p4=2 and not(blanco(p5)) and p5<>1 and p5<>2',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','P4=5_P5',241,TRUE,'Si es yerno/nuera debería ser unido/a, casado/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p4)) and p4=5 and not(blanco(p5) or p5=1 or p5=2 or nsnc(p5))',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p5_2_edad',241,TRUE,'Si es casado/a, en general, debería tener 18 años o más; si los datos son correctos detallar la situación',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p5)) and p5=2 and not(blanco(edad)) and not(nsnc(edad)) and edad<18',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p5_5_edad',241,TRUE,'Si es divorciado/a, en general, debería tener 18 años o más; si los datos son correctos detallar la situación',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p5)) and p5=5 and not(blanco(edad)) and not(nsnc(edad)) and edad<18',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p5_6_edad',241,TRUE,'Si es separado/a de matrimonio, en general, debería tener 18 años o más; si los datos son correctos detallar la situación',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p5)) and p5=6 and not(blanco(edad)) and not(nsnc(edad)) and edad<18',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p5_7_edad',241,TRUE,'Si es viudo/a de matrimonio, en general, debería tener 18 años o más; si los datos son correctos detallar la situación',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p5)) and p5=7 and not(blanco(edad)) and not(nsnc(edad)) and edad<18',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','P5_salto',241,TRUE,'Si es menor de 14 años, no debe tener dato en p5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(edad)) and not(nsnc(edad)) and edad<14 and not(blanco(p5))',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','P5b',250,TRUE,'Convive en pareja con alguien de este hogar, ¿quién es...?','numero','2',NULL,'Para personas de 14 años y más, unidas/casadas. Si convive con alguien de este hogar, anote el código del componente. (Si no convive, anote código 95)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p5b',NULL,'edad>=14 and (p5=1 or p5=2)',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','P5b_95',251,TRUE,'Si no convive con el cónyuge, aclarar las causas en observaciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p5b)) and p5b=95',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p5b<>p0',251,TRUE,'El número de miembro con el que convive debe ser distinto del número propio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p5b)) and p5b=persona',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','FILTRO','filtro_p6',252,TRUE,'24 años o menos',NULL,NULL,NULL,'Resto pasa a','P722',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'edad <25',NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','M.P_m','CP','P6',255,TRUE,'¿Quiénes son el padre y la madre de…',NULL,NULL,NULL,'Para personas de 24 años o menos. (Si no vive en el hogar anote 95)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P6','P','P6a',10,TRUE,'Padre/Madre','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p6a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P6','P','P6b',20,TRUE,'Madre/Padre','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p6b',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p4_p6_ayb',256,TRUE,'Si no es hijo/hijastro del respondiente, este no debería figurar como padre o madre en p6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(edad)) and not(nsnc(edad)) and edad<=24 and not(blanco(p4)) and p4<>3 and p4<>4 and not(blanco(p6a)) and not(blanco(p6b)) and (p6a=1 or p6b=1)',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p5b<>p6a',256,TRUE,'El miembro declarado como conviviente no puede ser el declarado como padre',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(edad)) and not(nsnc(edad)) and edad<25 and not(blanco(p5b)) and not(nsnc(p5b)) and p5b<>95 and not(blanco(p6a)) and p5b=p6a',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p5b<>p6b',256,TRUE,'El miembro declarado como conviviente no puede ser el declarado como madre',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(edad)) and not(nsnc(edad)) and edad<25 and not(blanco(p5b)) and p5b<>95 and not(nsnc(p5b)) and not(blanco(p6b)) and p5b=p6b',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p6a<>p0',256,TRUE,'El número de miembro del padre debe ser distinto del número propio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p6a)) and not(nsnc(p6a)) and not(blanco(edad)) and not(nsnc(edad)) and edad<25 and p6a>0 and p6a<95 and p6a=persona',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p6a<>p6b',256,TRUE,'El número de miembro declarado como padre debe ser distinto al de la madre',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(p6a)) and p6a>0 and p6a<95 and not(blanco(p6b)) and p6a=p6b',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','CONS','p6b<>p0',256,TRUE,'El número de miembro de la madre debe ser distinto del número propio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'not(blanco(edad)) and not(nsnc(edad)) and edad<25 and not(blanco(p6b)) and p6b>0 and p6b<95 and p6b=persona',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','P722',260,TRUE,'¿Se reconoce indígena o descendiente de pueblos indígenas u originarios?','si_no',NULL,NULL,'Para toda la población.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p722',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P722','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P722','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m','P','P825',270,TRUE,'¿Se reconoce afrodescendiente o tiene antepasados negros o africanos?','si_no',NULL,NULL,'Para toda la población.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'p825',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P825','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','P825','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025',NULL,'F','I1',60,TRUE,'Individual - componente seleccionado',NULL,NULL,NULL,NULL,NULL,'personas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:I1','B','Bloque_indiv',50,TRUE,'BLOQUE INDIVIDUAL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Bloque_indiv','P','MSI',70,TRUE,'Respondiente número','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'msi',NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','Bloque_indiv','P','MSNOMBREI',80,TRUE,'Nombre','texto','ancho',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'msnombrei',NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','Bloque_indiv','P','MSEDADI',90,TRUE,'Edad','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'msedadi',NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','F:I1','P','PREMS',140,TRUE,'¿La persona seleccionada está presente?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'entreaind','entreaind','vdominio=3',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','PREMS','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,'REAMS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','PREMS','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:I1','B','CONTACTOIND',150,TRUE,'CONTACTO DEL COMPONENTE SELECCIONADO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CONTACTOIND','CP','CONTACTOMS',10,TRUE,'Solicite los datos de contacto de la persona seleccionada y pacte cita.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CONTACTOMS','P','movili',2,TRUE,'Teléfono de contacto:','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'movili',NULL,'vdominio=3',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CONTACTOMS','P','correoi',3,TRUE,'Correo electrónico (e-mail):','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'correoi',NULL,'vdominio=3',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CONTACTOMS','P','fecha_cita',4,TRUE,'Volver a visitar el día:','fecha','10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'fecha_cita',NULL,'vdominio=3',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CONTACTOMS','P','hora_cita',5,TRUE,'A las:','hora','4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'hora_cita',NULL,'vdominio=3',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CONTACTOIND','P','RESULCITA',20,TRUE,'Retomar la entrevista','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'resulcita',NULL,'vdominio=3',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RESULCITA','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,'NACMS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RESULCITA','O','2',2,TRUE,'Ausente reiterado',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RESULCITA','O','3',3,TRUE,'Rechazo',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:I1','P','REAMS',160,TRUE,'¿La persona seleccionada aceptó responder el cuestionario individual?','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'reams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','REAMS','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','REAMS','O','2',2,TRUE,'No, rechazó',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:I1','CP','CONTACTOMS_2',170,TRUE,'¿Podría decirme su...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CONTACTOMS_2','P','TELMS',1,TRUE,'teléfono de contacto?','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'telms',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','CONTACTOMS_2','P','CORREOMS',2,TRUE,'correo electrónico (e-mail)?','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'correoms',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:I1','P','NACMS',180,TRUE,'¿Podría decirme el mes y el año de su nacimiento? (MM/AAAA)','texto','7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'nacms',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:I1','CONS','valid_NACMS',181,TRUE,'mes y año de nacimiento debe ingresarse con formato mm/aaaa',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'informado(nacms) and not(mesanio_valido(nacms))',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:I1','CONS','edad_nacms',182,TRUE,'La fecha de nacimiento no coincide con la edad ingresada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'informado(nacms) and informado(edad) and mesanio_valido(nacms) and informado(f_realiz_o) and fecha_valida(f_realiz_o) and not(edad_mes_annio_valido(edad, nacms,f_realiz_o))',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:I1','B','GGS',190,TRUE,'Generación y Género',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','GGS','P','ID_BLAISE',10,TRUE,'Número de ID','texto','9',NULL,'A cuestionario individual en Blaise',NULL,NULL,NULL,'ocultar',NULL,NULL,NULL,'id_blaise',NULL,'INHABILITAR',NULL,NULL,'false','true',NULL,NULL),
('GGS_2025','GGS','P','ID_BLAISE_PARSEADO',20,TRUE,'Número de ID','texto','11',NULL,'A cuestionario individual en Blaise',NULL,NULL,NULL,NULL,'ID BLAISE',NULL,NULL,'id_blaise_parseado',NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','F:I1','B','Bloque_resulI',200,TRUE,'BLOQUE RESULTADO DE ENTREVISTA INDIVIDUAL',NULL,NULL,NULL,'Complete al finalizar el cuestionario individual en sistema Blaise',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Bloque_resulI','P','FIN_1',10,TRUE,'¿Finalizó la entrevista?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'fin_1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_1','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,'FIN_3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_1','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Bloque_resulI','P','FIN_2',20,TRUE,'La entrevista no finalizó porque…','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'fin_2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_2','O','1',1,TRUE,'la persona seleccionada la interrumpió (cuestionario incompleto)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_2','O','2',2,TRUE,'tuvo problemas con el cuestionario individual en sistema Blaise',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_2','O','3',3,TRUE,'tuvo problemas con el dispositivo móvil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_2','O','4',4,TRUE,'Otra situación',NULL,NULL,NULL,'(especificar)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_2/4','P','escif',5,TRUE,NULL,'texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'escif',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Bloque_resulI','P','FIN_3',30,TRUE,'¿Pudo sincronizar el cuestionario individual en sistema Blaise?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'fin_3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_3','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','FIN_3','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025',NULL,'F','RE_SUP',120,TRUE,'SUPERVISIÓN GGS 2022',NULL,NULL,NULL,'ENCUESTA GENERACIÓN Y GÉNERO 2022',NULL,'viviendas',NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','TEXTO','ResFor',5,TRUE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','B','RE.1_sup',10,TRUE,'GGS_SUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RE.1_sup','P','vdominio_sup',10,TRUE,NULL,'numero','1',NULL,NULL,NULL,NULL,NULL,'ocultar',NULL,NULL,NULL,'vdominio_sup',NULL,'INHABILITAR',NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','RE.1_sup','P','s1a1_obs_sup',15,TRUE,'Observaciones','texto','ancho',NULL,NULL,NULL,NULL,NULL,NULL,'-','true',NULL,'s1a1_obs_sup','s1a1_obs_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','RE.1_sup','P','datos_personal_sup',27,TRUE,'Nombre y apellido del supervisor/a','texto','largo',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'datos_personal_sup','datos_personal_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','RE.1_sup','P','datos_personal_enc',28,TRUE,'Nombre y apellido del encuestador/a','texto','largo',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'datos_personal_enc',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','B','Visitas_sup',40,TRUE,'Visitas realizadas para completar la supervisión',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Visitas_sup','TEXTO','vis_enunciado_sup',42,TRUE,'Anote las visitas a la vivienda que haya realizado:',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','BF','BF_VIS_SUP',44,TRUE,'Visitas',NULL,'1',NULL,NULL,'VIS_SUP',NULL,'7',NULL,NULL,NULL,NULL,NULL,NULL,'total_vis_sup',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','total_vis_sup',50,TRUE,'Total visitas:','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'total_vis_sup','total_vis_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','soporte_sup',52,TRUE,'¿La supervisión se registra en papel o en Dispositivo Móvil?','opciones',NULL,NULL,NULL,NULL,NULL,NULL,'ocultar',NULL,NULL,NULL,'soporte_sup',NULL,'INHABILITAR',NULL,NULL,'false',NULL,NULL,'{"autoing":"2"}'),
('GGS_2025','soporte_sup','O','1',1,TRUE,'En Papel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','soporte_sup','O','2',2,TRUE,'En Dispostivo móvil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','Modo',58,TRUE,'Modo de realización de la entrevista','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'modo_sup','modo_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','Modo','O','1',1,TRUE,'Presencial',NULL,NULL,NULL,NULL,'sp1a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Modo','O','2',2,TRUE,'Telefónica',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','confir_tel_sup',60,TRUE,'Marque el número de teléfono y corrobore el mismo con la persona que contactó ("El número al que estoy hablando, ¿es el...?"). Si la respuesta es "No", pida disculpas, verifique el número y marque nuevamente. Supervisor/a: ¿Pudo comunicarse con alguien mediante el número registrado?','si_no','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'confir_tel_sup',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','confir_tel_sup','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','confir_tel_sup','O','2',2,TRUE,'No',NULL,NULL,NULL,'Pase a razon en S1_sup y marque la opción que corresponda en 7. Ausencia','total_h_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','domicilio_sup',64,TRUE,'Buenos días / buenas tardes. Llamo desde la Dirección General de Estadística y Censos de la Ciudad de Buenos Aires. Estamos realizando la supervisión de la Encuesta Generación y Género 2022; ya hemos contactado esta vivienda a través de un Encuestador/a. En este caso, realizaremos una breve entrevista telefónica. En primer lugar le pido que me confirme el domicilio en que fue encuestado/a: ¿Calle?... ¿Nº?... ¿Piso?... ¿Dpto.?...','texto','ancho',NULL,'Registrar y verificar coincidencia con la hoja de ruta',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'domicilio_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','confir_dom_sup',70,TRUE,'¿El domicilio declarado coincide con el de la hoja de ruta?','si_no',NULL,NULL,'Supervisor/a, no formule esta pregunta. Si coincide el domicilio, registre 1; en caso contrario, registre 2.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'confir_dom_sup',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','confir_dom_sup','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,'sp1b',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','confir_dom_sup','O','2',2,TRUE,'No',NULL,NULL,NULL,'Pase a razon en S1_sup y marque la opción 9.6 El número de teléfono registrado no corresponde al domicilio de la hoja de ruta','total_h_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','B','entreav_sup',74,TRUE,'SP1 Apertura de entrevista',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ocultar',NULL,NULL,NULL,NULL,NULL,'INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','B','Respon_sup',180,TRUE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Respon_sup','P','sp1a',190,TRUE,'¿Identificó la vivienda indicada en la hoja de ruta?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sp1a',NULL,NULL,'sp1a',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','sp1a','O','1',1,TRUE,'SÍ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','sp1a','O','2',2,TRUE,'No',NULL,NULL,NULL,'Pase a B.razon_viv_sup Razón por la cual la vivienda no existe','B.razon_viv_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','habita_sup',191,TRUE,'Esa vivienda, ¿se encuentra en condiciones de ser habitada?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'habita_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','habita_sup','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,'sp1b',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','habita_sup','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','construcción_sup',192,TRUE,'Construcción','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'construccion_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','construcción_sup','O','1',41,TRUE,'Se está construyendo',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','construcción_sup','O','2',42,TRUE,'Construcción paralizada',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','construcción_sup','O','3',43,TRUE,'Refacción',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','B','B.razon_viv_sup',193,TRUE,'Razón de no existencia.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_viv_sup','P','razon_viv_sup',194,TRUE,'Razón por la cual la vivienda no existe','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'razon_viv_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_viv_sup','O','2',2,TRUE,'Demolida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_viv_sup','O','6',6,TRUE,'Variaciones en el listado',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_viv_sup','P','razon_2_sup',610,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 2',NULL,NULL,'razon_2_sup','razon_2_sup','razon_viv_sup=2',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_2_sup','O','1',21,TRUE,'Fue demolida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_2_sup','O','2',22,TRUE,'En demolición',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_2_sup','O','3',23,TRUE,'Levantada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_2_sup','O','4',24,TRUE,'Tapiada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_viv_sup','P','razon_6_sup',615,TRUE,NULL,'opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'razón 6',NULL,NULL,'razon2_6_sup','razon2_6_sup','razon_viv_sup=6',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_6_sup','O','1',61,TRUE,'No existe lugar físico',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_6_sup','O','2',62,TRUE,'No es vivienda',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_6_sup','O','3',63,TRUE,'Existen otras viviendas',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_6_sup','O','4',64,TRUE,'Otro',NULL,NULL,NULL,'(especificar)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_6_sup/4','P','razon3_sup',8,TRUE,NULL,'texto','medio',NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,'razon3_sup','razon3_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','sp1b',200,TRUE,'En esa vivienda, ¿reside, al menos, un hogar particular?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sp1b',NULL,NULL,'sp1b',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','sp1b','O','1',1,TRUE,'SÍ',NULL,NULL,NULL,NULL,'sp1c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','sp1b','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','B','B.razon_hog_sup',205,TRUE,'Razón de no existencia.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog_sup','P','razon_hog_sup',206,TRUE,'Razón por la cual la vivienda no tiene habitantes permanentes','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'razon_hog_sup',NULL,'sp1b=2 or sp1b=-9',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_hog_sup','O','1',1,TRUE,'Deshabitada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_hog_sup','O','3',3,TRUE,'Fin de Semana',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_hog_sup','O','5',5,TRUE,'Vivienda usada como establecimiento',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_hog_sup','O','9',9,TRUE,'Otras causas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog_sup','P','razon_1_sup',610,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 1',NULL,NULL,'razon_1_sup','razon_1_sup','razon_hog_sup=1',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_1_sup','O','1',11,TRUE,'Venta o alquiler',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_1_sup','O','2',12,TRUE,'Sucesión o remate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_1_sup','O','3',13,TRUE,'Construcción reciente',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_1_sup','O','4',14,TRUE,'Sin causa conocida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog_sup','P','razon_3_sup',615,TRUE,NULL,'opciones',NULL,NULL,'Viven en otra vivienda la mayor parte...','fin',NULL,NULL,NULL,'razón 3','true',NULL,'razon2_3_sup','razon2_3_sup','razon_hog_sup=3',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_3_sup','O','1',31,TRUE,'de la semana',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_3_sup','O','2',32,TRUE,'del mes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_3_sup','O','3',33,TRUE,'del año',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog_sup','P','razon_5_sup',620,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 5',NULL,NULL,'razon2_5_sup','razon2_5_sup','razon_hog_sup=5',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_5_sup','O','1',51,TRUE,'Conserva comodidad de vivienda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','B.razon_hog_sup','P','razon_9v_sup',625,TRUE,NULL,'opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,'razón 9v',NULL,NULL,'razon_9v_sup','razon_9v_sup','razon_hog_sup=9',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_9v_sup','O','3',1,TRUE,'Problemas de seguridad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_9v_sup','O','4',2,TRUE,'Inaccesible',NULL,NULL,NULL,'(Problemas climáticos u otros)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_9v_sup','O','7',3,TRUE,'No salió a campo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_9v_sup','O','8',4,TRUE,'Reservado',NULL,NULL,NULL,'(Incluir la supervisión de una no realizada no encuestable en donde se detectó la existencia de un hogar)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','sp1c',208,TRUE,'¿Alguna persona residente en la vivienda accedió a responder la encuesta?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sp1c',NULL,NULL,'sp1c',NULL,NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','sp1c','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','sp1c','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,'total_h_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','sp3',210,TRUE,'¿Todas las personas que residen en esta vivienda comparten los gastos de comida?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sp3_sup','sp3_sup','sp1c=1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','sp3','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','sp3','O','2',2,TRUE,'No',NULL,NULL,NULL,'Recuerde supervisar a todos los hogares de la vivienda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:RE_SUP','P','total_h_sup',215,TRUE,'Total de hogares','numero','2',NULL,'Abra tantos cuestionarios S1_sup como cantidad de hogares',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'total_h_sup','total_h_sup','confir_tel_sup=2 or confir_dom_sup=2 or sp1c=2 or sp3_sup=1 or sp3_sup=2',NULL,NULL,'false',NULL,NULL,'{"autoing":"sp3_sup = 1 or confir_tel_sup=2 or confir_dom_sup=2or sp1c = 2=> 1"}'),
('GGS_2025','F:RE_SUP','BF','Botón_S1_SUP',245,TRUE,'Hogar',NULL,'1',NULL,NULL,'S1_SUP','viviendas','3',NULL,NULL,NULL,NULL,NULL,NULL,'total_h_sup',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025',NULL,'F','VIS_SUP',130,TRUE,'Visitas de la vivienda',NULL,NULL,NULL,NULL,NULL,'visitas_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:VIS_SUP','P','anoenc_sup',10,TRUE,'Nro Renglon','numero','2',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'anoenc_sup','anoenc_sup','INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS_SUP','P','rol_sup',20,TRUE,'Rol5','texto','corto',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'rol_sup','rol_sup','INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS_SUP','P','per_sup',30,TRUE,'Persona','numero','3',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'per_sup','per_sup','INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS_SUP','P','usu_sup',40,TRUE,'Usuario','texto','corto',NULL,NULL,NULL,NULL,NULL,'ocultar','-',NULL,NULL,'usu_sup','usu_sup','INHABILITAR',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS_SUP','P','fecha_sup',50,TRUE,'Fecha visita','fecha','10',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'fecha_sup','fecha_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS_SUP','P','hora_sup',60,TRUE,'Hora','hora','4',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'hora_sup','hora_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','F:VIS_SUP','P','anotacion_sup',70,TRUE,'Anotación','texto','ancho',NULL,NULL,NULL,NULL,NULL,NULL,'-','true',NULL,'anotacion_sup','anotacion_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025',NULL,'F','S1_SUP',140,TRUE,'SELECCIÓN',NULL,NULL,NULL,NULL,NULL,'hogares_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1_SUP','P','obs_hogar_sup',760,TRUE,'Observaciones del hogar','texto','ancho',NULL,NULL,NULL,NULL,NULL,NULL,'-','true',NULL,'obs_hogar_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1_SUP','FILTRO','Encuestables_sup',770,TRUE,NULL,NULL,NULL,NULL,NULL,'razon_noentrevista_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sp1c=1 or sp1c=2',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1_SUP','B','datosoriginal_sup',780,TRUE,'Datos de referencia de la encuesta original',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','datosoriginal_sup','P','Resp_comp_sup',31,TRUE,'Nombre del Respondiente de la carátula y de la composición del hogar','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'resp_comp_sup','resp_comp_sup',NULL,NULL,NULL,NULL,'true',NULL,'{"autoing":"nombrer"}'),
('GGS_2025','datosoriginal_sup','P','Resp_comp_ed_sup',33,TRUE,'Edad del Respondiente de la carátula y de la composición del hogar','numero','3',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'resp_comp_ed_sup','resp_comp_ed_sup',NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','datosoriginal_sup','P','Resp_indi_sup',36,TRUE,'Nombre del Respondiente del cuestionario Individual','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'resp_indi_sup','resp_indi_sup',NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','datosoriginal_sup','P','Resp_indi_ed_sup',38,TRUE,'Edad del Respondiente del cuestionario Individual','numero','3',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'resp_indi_ed_sup','resp_indi_ed_sup',NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','F:S1_SUP','B','Respon_hogar_sup',790,TRUE,'La persona que responde la supervisión debe ser la misma que respondió por la composición del hogar cuando pasó el encuestador/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Respon_hogar_sup','P','spr1',193,TRUE,'¿En este hogar hay al menos una persona de 18 a 79 años de edad?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'spr1_sup','spr1_sup','sp1c=1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','spr1','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','spr1','O','2',2,TRUE,'No',NULL,NULL,NULL,'Fin de la supervisión. Indique en Observaciones si hay alguna información adicional que considere relevante.','fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Respon_hogar_sup','P','entrea_sup',194,TRUE,'Apertura de entrevista','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'entrea_sup','entrea_sup','sp1c=2 or  spr1_sup= 1',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','entrea_sup','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','entrea_sup','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,'razon_noentrevista_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Respon_hogar_sup','P','sp4',198,TRUE,'El hogar, ¿fue entrevistado por el encuestador/a?','opciones',NULL,NULL,'(G-S)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sp4',NULL,'entrea_sup = 1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','sp4','O','1',1,TRUE,'Sí, en forma presencial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','sp4','O','2',2,TRUE,'Sí, por teléfono',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','sp4','O','3',3,TRUE,'No',NULL,NULL,NULL,'Fin de la supervisión. Indique en Observaciones si hay alguna información adicional que considere relevante.','fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','Respon_hogar_sup','P','sp5',200,TRUE,'Nombre de la persona respondiente de la supervisión','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'sp5_sup','sp5_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','Respon_hogar_sup','P','spr2',210,TRUE,'La persona que responde la supervisión, ¿coincide con la que respondió por la composición del hogar?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'spr2_sup','spr2_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','spr2','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','spr2','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','Respon_hogar_sup','P','fecha_realiz_sup',230,TRUE,'Fecha de realización','fecha','10',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'fecha_realiz_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"autoing":"hoy()"}'),
('GGS_2025','F:S1_SUP','B','M.P_sup',800,TRUE,'COMPONENTES DEL HOGAR Y SELECCIÓN',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_sup','P','nombres_componentes_sup',2,TRUE,'Por favor, nombre todas las personas que componen este hogar empezando por usted. No se olvide de Ud. ni de bebés, niñas y niños.','texto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'nombres_componentes_sup','nombres_componentes_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1_SUP','BF','BF_S1_P_SUP',810,TRUE,'Personas',NULL,'1',NULL,NULL,'S1_P_SUP',NULL,'3',NULL,NULL,NULL,NULL,NULL,NULL,'total_m_sup',NULL,NULL,NULL,NULL,NULL,'{"camposResumen":["nombre_sup","sexo_sup","edad_sup"]}'),
('GGS_2025','F:S1_SUP','B','S1.2',850,TRUE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','S1.2','P','total_m_sup',10,TRUE,'Total de componentes del hogar','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'total_m_sup','total_m_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','S1.2','P','SORTEO_SUP',15,TRUE,'¿Esas son todas las personas que componen el hogar (incluidas las ausentes)?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sorteo_sup',NULL,'_personas_incompletas_sup=0',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','SORTEO_SUP','O','1',10,TRUE,'Sí, son todas. Proceder al sorteo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SORTEO_SUP','O','2',20,TRUE,'No, faltó anotar a alguien',NULL,NULL,NULL,NULL,'total_m_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','S1.2','P','total_rango_sup',20,TRUE,'Total de personas en el rango de edad','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'total_rango_sup','total_rango_sup','!!total_rango_sup',NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','S1.2','P','nro_miembro_sel_sup',25,TRUE,'N° de componente seleccionado','numero','2',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'nro_miembro_sel_sup','nro_miembro_sel_sup','!!total_rango_sup',NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','S1.2','P','nombre_miembro_sel_sup',30,TRUE,'Nombre del componente seleccionado','texto','medio',NULL,NULL,NULL,NULL,NULL,NULL,'-',NULL,NULL,'nombre_miembro_sel_sup',NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','S1.2','P','nro_mie_sel_ing_sup',35,TRUE,'N° Ingresado componente seleccionado','numero','2',NULL,'Si la encuesta se realizó en PAPEL',NULL,NULL,NULL,'ocultar',NULL,'true',NULL,'nro_mie_sel_ing_sup',NULL,'soporte_sup=1',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','S1.2','P','spr3',35,TRUE,'La persona seleccionada en la supervisión para contestar el cuestionario individual, ¿coincide con la selección que hizo el encuestador/a?','si_no',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'spr3_sup','spr3_sup',NULL,NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','spr3','O','1',1,TRUE,'Sí',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','spr3','O','2',2,TRUE,'No',NULL,NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','S1.2','CP','razon_noentrevista_sup',45,TRUE,'Razón no entrevista',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_noentrevista_sup','P','razon1_sup',10,TRUE,'Razón de no entrevista','opciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'razon1_sup',NULL,'confir_tel_sup=2 or confir_dom_sup=2 or sp1c=2 or sp3_sup=1 or sp3_sup=2 or entrea_sup=2',NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon1_sup','O','7',1,TRUE,'Ausencia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon1_sup','O','8',2,TRUE,'Rechazo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon1_sup','O','9',3,TRUE,'Otras causas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_noentrevista_sup','P','razon_7_1h_sup',140,TRUE,'Ausencia','opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,'razon_7_1h_sup','razon_7_1h_sup','razon1_sup=7',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_7_1h_sup','O','1',71,TRUE,'No se pudo contactar en 3 visitas',NULL,NULL,NULL,'(presenciales o telefónicas)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7_1h_sup','O','2',72,TRUE,'Por causas circunstanciales',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7_1h_sup','O','3',73,TRUE,'Viaje',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7_1h_sup','O','4',74,TRUE,'Vacaciones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7_1h_sup','O','5',75,TRUE,'Problemas con el dispositivo móvil',NULL,NULL,NULL,'(Robo, falla del servidor o del dispositivo, etc.)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_7_1h_sup','O','6',76,TRUE,'Problemas con el teléfono',NULL,NULL,NULL,'(No corresponde, interferencia constante, dificultades en la red, etc.). Sólo para supervisiones telefónicas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_noentrevista_sup','P','razon_8_1h_sup',150,TRUE,'Rechazo','opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,'razon_8_1_sup','razon_8_1_sup','razon1_sup=8',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_8_1h_sup','O','1',81,TRUE,'Negativa rotunda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_8_1h_sup','O','2',82,TRUE,'Rechazo por portero eléctrico o teléfono',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_8_1h_sup','O','3',83,TRUE,'Se acordaron visitas que no se concretaron',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_noentrevista_sup','P','razon_9_1h_sup',160,TRUE,'Otras Causas','opciones',NULL,NULL,NULL,'fin',NULL,NULL,NULL,NULL,NULL,NULL,'razon_9_1h_sup','razon_9_1h_sup','razon1_sup=9',NULL,NULL,'false',NULL,NULL,NULL),
('GGS_2025','razon_9_1h_sup','O','2',92,TRUE,'Duelo, alcoholismo, discapacidad, idioma extranjero',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','razon_9_1h_sup','O','6',93,TRUE,'El número de teléfono no corresponde al domicilio de la hoja de ruta',NULL,NULL,NULL,'Sólo para supervisiones telefónicas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025',NULL,'F','S1_P_SUP',150,TRUE,'LISTADO DE LOS COMPONENTES',NULL,NULL,NULL,NULL,NULL,'personas_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','F:S1_P_SUP','B','M.P_m_sup',800,TRUE,'LISTADO DE LOS COMPONENTES DEL HOGAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m_sup','P','SP1_SUP',10,TRUE,'Por favor, nombre todas las personas que componen este hogar, empezando por usted.','texto','ancho',NULL,'Nombre o sobrenombre. (No se olvide de Ud. ni de bebés, niñas y niños)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'nombre_sup','nombre_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m_sup','P','SP2a_SUP',20,TRUE,'Sexo registrado al nacer','opciones','1',NULL,'(Anote el código)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sexo_sup','sexo_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP2a_SUP','O','1',1,TRUE,'Varón',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','SP2a_SUP','O','2',2,TRUE,'Mujer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','M.P_m_sup','P','SP3b_SUP',40,TRUE,'¿Cuántos años cumplidos tiene en este momento?','numero','3',NULL,'(Si tiene menos de un año anote 0)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'edad_sup','edad_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m_sup','P','SP4_SUP',45,TRUE,'¿Qué parentesco tiene con usted?','opciones','3',NULL,'(E-S)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sp4_sup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','1',1,TRUE,'Respondiente',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','2',2,TRUE,'Cónyuge/pareja',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','3',3,TRUE,'Hijo/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','4',4,TRUE,'Hijastro/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','5',5,TRUE,'Yerno o nuera',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','6',6,TRUE,'Nieto/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','7',7,TRUE,'Padre/madre/suegro/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','8',8,TRUE,'Hermano/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','9',9,TRUE,'Cuñado/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','10',10,TRUE,'Sobrino/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','11',11,TRUE,'Abuelo/a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','12',12,TRUE,'Otro/a familiar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP4_SUP','O','14',14,TRUE,'Otro/a no familiar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GGS_2025','M.P_m_sup','P','SPl0_SUP',50,TRUE,'Letra de orden según edad','texto','ancho',NULL,'Para personas de 18 años a 79 años. Comience con la letra A a partir de la persona de mayor edad y continúe con la letra B y subsiguientes.',NULL,NULL,NULL,NULL,NULL,'true',NULL,'spl0_sup',NULL,'!!spl0_sup or (edad_sup>=18 )',NULL,NULL,NULL,'true',NULL,NULL),
('GGS_2025','M.P_m_sup','P','SP5_SUP',70,TRUE,'¿Actualmente es...','opciones',NULL,NULL,'(G-S) Para personas de 14 años y más (Anote código)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'spp5','spp5','edad_sup>=14','99',NULL,NULL,NULL,NULL,NULL),
('GGS_2025','SP5_SUP','O','1',1,TRUE,'unido/a?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','SP5_SUP','O','2',2,TRUE,'casado/a?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','SP5_SUP','O','3',3,TRUE,'separado/a de unión?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','SP5_SUP','O','4',4,TRUE,'viudo/a de unión?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','SP5_SUP','O','5',5,TRUE,'divorciado/a?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','SP5_SUP','O','6',6,TRUE,'separado/a de matrimonio?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','SP5_SUP','O','7',7,TRUE,'viudo/a de matrimonio?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025','SP5_SUP','O','8',8,TRUE,'soltero/a, nunca casado/a ni unido/a?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'true',NULL,NULL,NULL),
('GGS_2025',NULL,'FIN','fin',9999,TRUE,'Muchas gracias por su tiempo y su colaboración.',NULL,NULL,NULL,'Fin del cuestionario',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
